### ISSUE TITLE
digit touch forces on heavy mass objects

### ISSUE THREAD

**Issue by shivanimall** [facebookresearch/tacto#17]
Hello,

I have a few  digit related questions:
1/ I understand that digit is just another mesh object, that is loaded into bullet like any other collision object. but wondering if there are any units/size/mass of the default loaded digit object? and any function to change these default values?

2/ Let's say I have a heavy mass object B and I am using digit to generate touch forces on it. I do get some force values, but these don't seem realistic when comparing the relative mass sizes of the default-loaded digit and object B. I'm using `globalScaling` parameter into loadURDF while loading digit currently to do some relative scaling. But, how do you recommend scaling digit relative to object B to generate realistic touch forces? is it necessary? or do you recommend using multiple digits? 

Please let me know if my question is unclear. Thanks.

**Comment by wx405557858** [comment]
Hi @shivanimall ,

1). the digit is loaded in `meshes/digit.urdf`. all the units are by default now, but they can be changed in the urdf.

2). I'm not sure whether I get the question correctly. Is the question that the forces are not correlated with the geometric shape size? From my understanding, changing the `<mass>` and `<inertia>` in the URDF might be helpful: [link](http://wiki.ros.org/urdf/Tutorials/Adding%20Physical%20and%20Collision%20Properties%20to%20a%20URDF%20Model)

**Comment by shivanimall** [comment]
thanks for the response @wx405557858.

Yeah my concern is that the forces may not be correlated to the geometric shape/mass/size if I am using a small digit sensor on a large/heavy-mass object. This is my intuition, but please correct me if I am wrong.

From my understanding, 
1/ the digit urdf is attached to an actual sensor. If I change the default size/mass of digit, would it still give me realistic sensor readings for the depth/rgb maps?

2/ On a heavy mass object, I would like to have a large digit sensor and apply a proportionally larger force, so for that I may want to change the mass/size of the digit. Is that okay to do? (from the backend sensor/tacto view, in case this may not work) 

Please let me know if I am unclear, thank you!

**Comment by wx405557858** [comment]
Got it. 

1/ Changing the mass of a digit is definitely fine!

2/ Changing the size of a digit may influence the output. I remembered we haven't implemented automatic scaling yet, because we assume the STL is about the size of a real DIGIT sensor. Changing the size of the object should be equivalent? 

In terms of forces, I think pybullet should allow large forces even for small objects. So it should be fine to use the default digit sensor. If you worry about picking up heavy objects, then changing friction (e.g. lateral_friction, rolling_friction, spinning_friction) in urdf might be helpful.

Also, in tacto, the relationship between force and deformation can be adjusted, in case that might be helpful for larger range of forces:

in
https://github.com/facebookresearch/tacto/blob/master/tacto/config_digit.yml

```
  force:
    enable: True # flag for enable force feedback. When enabled, the larger normal force is, the closer object is adjusted to the sensor.
    range_force: [0, 100] # dynamic range of forces used to simulate the elastomer deformation
    max_deformation: 0.005 # max pose depth adjustment, in meters
```

**Comment by shivanimall** [comment]
thanks @wx405557858 will try this out and let you know if I run into issues. 
thanks for pointing out deformation, that would have been a concern too.
